### PR TITLE
Set Smooth CPU Priority for Meteo-Qt

### PR DESCRIPTION
**Pull request by juancarlospaco**
- Set Smooth CPU Priority for Meteo-Qt.
- Makes `CTRL + C` work again on PyQt _(eg. when run from Terminal)_
- Bump Version.

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Not just only that CTRL + C failing is a Bug, but actually the App ignores a standard Unix signal to kill itself, also a Bug.


Nice 19 makes it run smoothly, yes I know it runs every 15 minutes,
when I am on an Online Game frame rate per second (FPS) drops every 15 minutes, and theres no need for that.

**Comment by juancarlospaco** [comment]
Hi, is this still maintained ?

**Comment by dglent** [comment]
Hi,
I don't know yet what to do with this.
Could you open an issue ?
I'd prefer to discuss it with others.

I wouldn't like to introduce changes which apply a system administration by the program. Personally i prefer to leave it as is and apply such settings locally.

**Comment by juancarlospaco** [comment]
It its not a system administration, it is not a system-wide administration, it is nothing system-wide.

On Linux every app can have this setting set by itself. 
I do it since years on all my apps.

**Pull request closed without merging**
