### PR TITLE
Update Slovak and Czech translation + lupdate

### PR DESCRIPTION
**Pull request by jose1711**

### CODE REVIEW

**Comment by dglent** [comment]
Could you update also in transifex as i pull from there regularly the translation files ?
Thanks

**Comment by jose1711** [comment]
I don't seem to have an option to upload a `.ts` file. Is there a way to push it from your side?

**Comment by dglent** [comment]
Can you upload manualy in transifex platform please ?


Την ημέρα Δευτέρα, 10 Ιουνίου 2019 8:30:32 Π.Μ. CEST, ο/η Jose Riha έγραψε:
> I don't seem to have an option to upload a .ts file. Is there a 
> way to push it from your side?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Dimitrios Glentadakis

**Comment by jose1711** [comment]
I have finally found the correct place to click.. uploaded

**Pull request merged**
